### ISSUE TITLE
tips for Nibbler

### ISSUE THREAD

**Issue by tissatussa** [rooklift/nibbler#171]
i managed to make Nibbler work on my Linux (with Electron) and i like Nibbler!

i'm not yet using it for Leela, i use it for regular UCI engines like SF.
the display is somewhat minimal, i have some ideas :

* show which engine is active
* show which NNUE is active

* after halt : show calculation duration of the last performed "go" command

* prefix move number index : #1 is best move (until now), last # will be the amount of legal moves in the position, which is nice data .. i like the way you show all legal moves : the ones which were never considered by the engine, at any depth, have a "?" indicator, while other moves have their last eval value and they are blue when in the current MPV range.

* when stopping the engine : display "best move" (which should be output by any UCI engine), which can differ (!) from the move on top in the current depth - this is my experience with testing UCI engines.

* format the eval value, maybe reserve a space for the "+" sign to make the pv variations align properly

**Comment by rooklift** [comment]
> show which engine is active
> show which NNUE is active

These are available in File --> About. I grant you this is not exactly obvious, but I don't know where else to put things, I try to keep space used to a minimum.

> after halt : show calculation duration of the last performed "go" command

Is that different from the time elapsed at the top right?

> the ones which were never considered by the engine

It's rather that they were never *reported* by the engine, they must have been considered, but they were never good enough to be in the list of best moves.

> display "best move" (which should be output by any UCI engine)

This is awkward because (a) I don't know where to put it, and (b) in the case of Leela, any discrepancy with the analysis output will be due to Leela's Temperature option, which helps Leela play varied moves but isn't interesting for analysis purposes.

**Comment by tissatussa** [comment]
you say 
> ... to put things, I try to keep space used to a minimum...
you can add a menu item to yes/no display such extra info eg. on top of the pv lines ?

after halting the engine i see the info line "stopped, halt, stopped" above the pv lines .. no time / duration info !?

about displaying ""best move" : i think when general UCI engines can be used with Nibbler, they should be supported properly (although maybe minimalistic) .. doesn't Leela use the UCI protocol regarding "best move" as i stated ?

some more ideas :

* smaller font size(s)
* MPV more then 5 (which i use often)

**Comment by rooklift** [comment]
> after halting the engine i see the info line "stopped, halt, stopped" above the pv lines .. no time / duration info !?

Oh, turn off Dev --> Show engine state

> MPV more then 5 (which i use often)

High values are really weakening for A/B engines (the setting isn't used for Leelaish engines). Really Nibbler remains basically a Leela GUI which supports other engines as an afterthought.
