### ISSUE TITLE
Code to parse UCI moves 

### ISSUE THREAD

**Issue by v11580** [rooklift/nibbler#254]
Nibbler has code to read UCI moves at  nice_movegen()  in 40_position.js line 1050.
However, the functionality is not incorporated in the pgn parser.

 Fore example, 1. e2e4 g8f6 throws an error.

**Comment by rooklift** [comment]
Allowing UCI moves seems like it should be simple, except I think there's the following complication:

* Internally Nibbler uses Chess960 format for castling, e.g. e1h1
* So moves like e1g1 would have to be converted to e1h1
* But only if there's a king on e1 (because some other piece could move from e1 to g1)
* But if it's actually a Chess960 game then e1g1 could be the correct castling move after all

Still, I'm thinking about it...

**Comment by rooklift** [comment]
Well, hopefully [this commit](https://github.com/rooklift/nibbler/commit/cfe8febbd7a524f01416e51b22942cf5cefef784) adds what you're looking for.

**Comment by rooklift** [comment]
OK, initial tests suggest there's some bug in that code. Looking into it...

**Comment by v11580** [comment]
Wow! Awesome response time.  I was under the impression Nibbler was no longer being maintained after reading some exchanges in other threads.  

This is an awesome program and thank you!

**Comment by rooklift** [comment]
It's true, I barely maintain it. But this was simple enough and it's actually something I had wanted in the past at some point.
